### ISSUE TITLE
Minor - POM property should reference <core-metadata-client> (line 37)?

### ISSUE THREAD

**Issue by gcloughley** [edgexfoundry/core-data#15]
https://github.com/edgexfoundry/core-data/blob/master/pom.xml

	<properties>
		<springmvc.raml.version>0.8.1</springmvc.raml.version>
		<spring.cloud.version>Brixton.SR5</spring.cloud.version>
		<activemq.version>5.7.0</activemq.version>
		<xbean.version>4.4</xbean.version>
		<paho.version>1.0.2</paho.version>
		<zeromq.version>0.3.6</zeromq.version>
		<core-domain.version>1.0.0-SNAPSHOT</core-domain.version>
		<core-exception.version>1.0.0-SNAPSHOT</core-exception.version>
		**<metadata-client.version>1.0.0-SNAPSHOT</metadata-client.version>**
		<core-test.version>1.0.0-SNAPSHOT</core-test.version>
		<support-logging-client.version>1.0.0-SNAPSHOT</support-logging-client.version>
		<assembley-plugin.version>2.5.5</assembley-plugin.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<nexusproxy>https://nexus.edgexfoundry.org</nexusproxy>
		<repobasepath>content/repositories</repobasepath>
		<checkstyle.plugin.version>2.17</checkstyle.plugin.version>
</properties>

**Comment by trcox** [comment]
Thanks Graeme!
