### ISSUE TITLE
Docker "latest" tag used for mongo

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/core-data#28]
Release: Barcelona

core-data depends on mongoDB.  The current DockerFile for mongo uses the latest tag, which isn't a good idea for production software.  We should instead use a specific version tag, otherwise it's possible that the behavior of an instance of Barcelona over time could change as the latest tag is updated to point to newer versions of mongo.

For more details see:
 * https://github.com/edgexfoundry/docker-edgex-mongo/blob/master/Dockerfile
 * https://hub.docker.com/_/mongo/

Also curious as to why this repository doesn't have any kind of version or release tag?

**Comment by trcox** [comment]
For reference, the MongoDB version in our image is 3.4.9. I'll submit a PR for this, then we can tag it for 0.2.0 and 0.2.1.
